config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'home/index'
  end

  # http://localhost:3000/users/sign_in
  devise_for :users, path: 'users',
                     controllers: {
                       sessions: 'users/devise/sessions',
                       passwords: 'users/devise/passwords',
                       registrations: 'users/devise/registrations'
                     }

  # http://localhost:3000/admins/sign_in
  devise_for :admins, path: 'admins',
                      controllers: {
                        sessions: 'admins/devise/sessions',
                        passwords: 'admins/devise/passwords',
                        registrations: 'admins/devise/registrations'
                      }

  authenticated :user do
    root 'users/home#index', as: :auth_user_root
  end

  authenticated :admin do
    root 'admins/home#index', as: :auth_admin_root
  end

  namespace :admins do
    get 'home/index'
    # resource  :home_page,        only: [:index]
  end
  get '/admins', to: 'admins/home#index', as: :admins

  namespace :users do
    get 'home/index'
    # resource  :home_page,        only: [:index]
  end
  get '/users', to: 'users/home#index', as: :users

  match '/users/:id', to: 'users/home#show', via: 'get', as: :user
  # match '/users', to: 'users#index', via: 'get'

  resources :plans

  resources :training_sessions
  resources :workouts
  resources :exercises
  resources :workout_sets

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'home/index'
  root 'home#index'
end

app/models/workout_set.rb
class WorkoutSet < ApplicationRecord
  GRIPS = %w[none pronated suppinated narrow wide]
  validates :repetition, :tempo, :pause, :series, presence: true
  validates :repetition, :tempo, :pause, numericality: { greater_than: 0 }

  belongs_to :workout
  belongs_to :exercise
end

app/controllers/workout_sets_controller.rb
class WorkoutSetsController < ApplicationController
  before_action :set_workout_set, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /workout_sets or /workout_sets.json
  def index
    @workout_sets = WorkoutSet.all
  end

  # GET /workout_sets/1 or /workout_sets/1.json
  def show; end

  # GET /workout_sets/new
  def new
    @workout_set = WorkoutSet.new
  end

  # GET /workout_sets/1/edit
  def edit
    @grips = %w[none pronated suppinated narrow wide]
  end

  # POST /workout_sets or /workout_sets.json
  def create
    @grips = %w[none pronated suppinated narrow wide]
    @workout_set = WorkoutSet.first_or_create_by(workout_set_params)
    # @workout_set = WorkoutSet.new(workout_set_params)

    respond_to do |format|
      if @workout_set.save
        format.html { redirect_to workout_set_url(@workout_set), notice: 'Workout set was successfully created.' }
        format.json { render :show, status: :created, location: @workout_set }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workout_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workout_sets/1 or /workout_sets/1.json
  def update
    respond_to do |format|
      if @workout_set.update(workout_set_params)
        format.html { redirect_to workout_set_url(@workout_set), notice: 'Workout set was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout_set }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workout_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_sets/1 or /workout_sets/1.json
  def destroy
    @workout_set.destroy

    respond_to do |format|
      format.html { redirect_to workout_sets_url, notice: 'Workout set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_workout_set
    @workout_set = WorkoutSet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def workout_set_params
    params.require(:workout_set).permit(:workout_id, :exercise_id, :series, :grip, :repetition_id, :tempo_id, :pause_id)
  end
end

app/helpers/workout_sets_helper.rb
module WorkoutSetsHelper
end

app/views/workout_sets/_form.html.erb
<%= form_with(model: workout_set) do |form| %>
  <% if workout_set.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(workout_set.errors.count, "error") %> prohibited this workout_set from being saved:</h2>

      <ul>
        <% workout_set.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :workout_id, style: "display: block" %>
    <%= form.text_field :workout_id %>
  </div>

  <div>
    <%= form.label :exercise_id, style: "display: block" %>
    <%= form.text_field :exercise_id %>
  </div>

  <div>
    <%= form.label :series, style: "display: block" %>
    <%= form.text_field :series %>
  </div>

  <div>
    <%= form.label :grip, style: "display: block" %>
    <%= form.collection_select :day, @grips, :to_s, :to_s, include_blank: false %>
  </div>

  <div>
    <%= form.label :repetition_id, style: "display: block" %>
    <%= form.text_field :repetition_id %>
  </div>

  <div>
    <%= form.label :tempo_id, style: "display: block" %>
    <%= form.text_field :tempo_id %>
  </div>

  <div>
    <%= form.label :pause_id, style: "display: block" %>
    <%= form.text_field :pause_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workout_sets/_workout_set.html.erb
<div id="<%= dom_id workout_set %>">
  <p>
    <strong>Workout:</strong>
    <%= workout_set.workout_id %>
  </p>

  <p>
    <strong>Exercise:</strong>
    <%= Exercise.find_by(workout_set.exercise_id).title %>
  </p>

  <p>
    <strong>Repetition:</strong>
    <%= workout_set.repetition %>
  </p>

  <p>
    <strong>Tempo:</strong>
    <%= workout_set.tempo %>
  </p>

  <p>
    <strong>Pause:</strong>
    <%= workout_set.pause %>
  </p>

</div>

app/views/workout_sets/edit.html.erb
<h1>Editing workout set</h1>

<%= render "form", workout_set: @workout_set %>

<br>

<div>
  <%= link_to "Show this workout set", @workout_set %> |
  <%= link_to "Back to workout sets", workout_sets_path %>
</div>

app/views/workout_sets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Workout sets</h1>

<div id="workout_sets">
  <% @workout_sets.each do |workout_set| %>
    <%= render workout_set %>
    <p>
      <%= link_to "Show this workout set", workout_set %>
    </p>
  <% end %>
</div>

<%= link_to "New workout set", new_workout_set_path %>

app/views/workout_sets/new.html.erb
<h1>New workout set</h1>

<%= render "form", workout_set: @workout_set %>

<br>

<div>
  <%= link_to "Back to workout sets", workout_sets_path %>
</div>

app/views/workout_sets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @workout_set %>

<div>
  <%= link_to "Edit this workout set", edit_workout_set_path(@workout_set) %> |
  <%= link_to "Back to workout sets", workout_sets_path %>

  <%= button_to "Destroy this workout set", @workout_set, method: :delete %>
</div>