config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'home/index'
  end

  # http://localhost:3000/users/sign_in
  devise_for :users, path: 'users',
                     controllers: {
                       sessions: 'users/devise/sessions',
                       passwords: 'users/devise/passwords',
                       registrations: 'users/devise/registrations'
                     }

  # http://localhost:3000/admins/sign_in
  devise_for :admins, path: 'admins',
                      controllers: {
                        sessions: 'admins/devise/sessions',
                        passwords: 'admins/devise/passwords',
                        registrations: 'admins/devise/registrations'
                      }

  authenticated :user do
    root 'users/home#index', as: :auth_user_root
  end

  authenticated :admin do
    root 'admins/home#index', as: :auth_admin_root
  end

  namespace :admins do
    get 'home/index'
    # resource  :home_page,        only: [:index]
  end
  get '/admins', to: 'admins/home#index', as: :admins

  namespace :users do
    get 'home/index'
    # resource  :home_page,        only: [:index]
  end
  get '/users', to: 'users/home#index', as: :users

  match '/users/:id', to: 'users/home#show', via: 'get', as: :user
  # match '/users', to: 'users#index', via: 'get'

  resources :plans

  resources :training_sessions
  resources :workouts
  resources :exercises
  resources :workout_sets

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'home/index'
  root 'home#index'
end

app/models/training_session.rb
class TrainingSession < ApplicationRecord
  belongs_to :workout, counter_cache: true
  belongs_to :plan, optional: true
  belongs_to :user, optional: true, counter_cache: true
end

app/controllers/training_sessions_controller.rb
class TrainingSessionsController < ApplicationController
  before_action :set_training_session, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /training_sessions or /training_sessions.json
  def index
    @training_sessions = TrainingSession.all
    @trainings = current_user.training_sessions
  end

  # GET /training_sessions/1 or /training_sessions/1.json
  def show
    @workout = @training_session.workout
  end

  # GET /training_sessions/new
  def new
    @training_session = TrainingSession.new
  end

  # GET /training_sessions/1/edit
  def edit; end

  # POST /training_sessions or /training_sessions.json
  def create
    @training_session = TrainingSession.new(training_session_params)

    respond_to do |format|
      if @training_session.save
        format.html do
          redirect_to training_session_url(@training_session), notice: 'Training session was successfully created.'
        end
        format.json { render :show, status: :created, location: @training_session }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @training_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /training_sessions/1 or /training_sessions/1.json
  def update
    respond_to do |format|
      if @training_session.update(training_session_params)
        format.html do
          redirect_to training_session_url(@training_session), notice: 'Training session was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @training_session }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @training_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_sessions/1 or /training_sessions/1.json
  def destroy
    @training_session.destroy

    respond_to do |format|
      format.html { redirect_to training_sessions_url, notice: 'Training session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_training_session
    @training_session = TrainingSession.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def training_session_params
    params.require(:training_session).permit(:plan_id, :user_id, :start_time, :workout_id, workout_id: [])
  end
end

app/helpers/training_sessions_helper.rb
module TrainingSessionsHelper
end

app/views/training_sessions/_form.html.erb
<%= form_with(model: training_session) do |form| %>
  <% if training_session.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(training_session.errors.count, "error") %> prohibited this training_session from being saved:</h2>

      <ul>
        <% training_session.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :workout_id, class: 'form-label' %>
    <%= form.collection_select :workout_id, Workout.all, :id, :title, { promt: "Select a Workout"}, { class: 'form-select'} %>
  </div>

  <div class="mb-3">
    <%= form.label :plan_id, class: "form-label" %>
    <%= form.collection_select :plan_id, Plan.all, :id, :title, { promt: "Select a Workout"}, { class: 'form-select'} %>
  </div>

  <div class="mb-3">
    <%= form.label :user_id, class: "form-label" %>
    <%= form.collection_select :user_id, User.all.order(:username), :id, :username, { promt: "Select a Workout", default: :current_user }, { class: 'form-select disabled'} %>
  </div>

  <div class="mb-3">
    <%= form.label :start_time, class: "form-label" %>
    <%= form.datetime_select :start_time, as: :date, html5: true, :class => 'form-control' %>
  </div>
  <br>

  <div class="float-start">
    <%= button_to "Create", @training_session, method: :update, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/training_sessions/_training_session.html.erb
<div id="<%= dom_id training_session %>">
  <H2>
    <%= training_session.workout.title %>
  </H2>
  <p>
    <%= training_session.workout.created_at.to_formatted_s(:short) %>, Part of <%= training_session.plan.title %>
  </p>
</div>

app/views/training_sessions/edit.html.erb
<h1>Editing training session</h1>

<%= render "form", training_session: @training_session %>

<div class="float-end">
  <%= link_to '<i class="bi bi-arrow-return-left"></i>'.html_safe, training_sessions_path, :class => "btn btn-outline-primary"%>
</div>

app/views/training_sessions/index.html.erb
<h1>Training Planer</h1>

<br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Calendar</h5>
    <%= week_calendar(events: @trainings ) do |date, trainings| %>
      <%= date.to_formatted_s(:short) %>
      <br>
      <% trainings.each do |tr| %>
        <b><%= link_to tr.workout.title, training_session_path(tr) %></b><br>
      <% end %>
    <% end %>
  </div>
</div>

<br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Trainings</h5>
    <div class="table-reponsive">
      <table class="table">
        <thead class="table-dark">
          <tr>
            <th>Scheduled</th>
            <th>Workout</th>
            <th>Plan</th>
            <td></td>
          </tr>
        </thead>
        <tbody>
          <% @training_sessions.each do |tr| %>
            <tr>
              <td><%= tr.start_time %></td>
              <td><%= tr.workout.title %></td>
              <td><%= tr.plan.title %></td>
              <td>
                <% if current_user.coach? %>
                  <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_training_session_path(tr) %>
                <% end %>
                <%= link_to '<i class="bi bi-eye"></i>'.html_safe, tr %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>
<div class="btn btn-outline-primary float-end">
  <i class="bi bi-plus" aria-hidden="true"></i>
  <%= link_to "New Training", new_training_session_path,  :class => "btn" %>
</div>

app/views/training_sessions/new.html.erb
<h1>New training session</h1>

<%= render "form", training_session: @training_session %>

<%= link_to "Back", workouts_path, :class => "btn btn-outline-primary float-end"%>

app/views/training_sessions/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @training_session.workout.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @training_session.workout.created_at %></h6>
    <p class="card-text"><%= @training_session.plan.title %></p>
  </div>
</div>

<br>
<table class="table">
  <thead class="table-dark">
    <tr>
      <th>Exercise</th>
      <th>Series</th>
      <th>Repetitions</th>
      <th>Tempo</th>
      <th>Pause</th>
    </tr>
  </thead>
  <tbody>
    <% @workout.workout_sets.each do |set| %>
      <tr>
        <td><%= set.exercise.title %></td>
        <td><%= set.series %></td>
        <td><%= set.repetition %></td>
        <td><%= set.tempo %></td>
        <td><%= set.pause %></td>
      </tr>
    <% end %>
  </tbody>

</table>
<br>

<div class="float-end">
  <%= link_to '<i class="bi bi-pencil-square"></i>'.html_safe, edit_training_session_path(@training_session), :class => "btn btn-outline-primary" %>
  <%= link_to '<i class="bi bi-arrow-return-left"></i>'.html_safe, training_sessions_path, :class => "btn btn-outline-primary"%>

</div>

<div class="float-start">
  <%= button_to "Delete", @training_session, method: :delete, :class => "btn btn-danger" %>
</div>