config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'home/index'
  end

  # http://localhost:3000/users/sign_in
  devise_for :users, path: 'users',
                     controllers: {
                       sessions: 'users/devise/sessions',
                       passwords: 'users/devise/passwords',
                       registrations: 'users/devise/registrations'
                     }

  # http://localhost:3000/admins/sign_in
  devise_for :admins, path: 'admins',
                      controllers: {
                        sessions: 'admins/devise/sessions',
                        passwords: 'admins/devise/passwords',
                        registrations: 'admins/devise/registrations'
                      }

  authenticated :user do
    root 'users/home#index', as: :auth_user_root
  end

  authenticated :admin do
    root 'admins/home#index', as: :auth_admin_root
  end

  namespace :admins do
    get 'home/index'
    # resource  :home_page,        only: [:index]
  end
  get '/admins', to: 'admins/home#index', as: :admins

  namespace :users do
    get 'home/index'
    # resource  :home_page,        only: [:index]
  end
  get '/users', to: 'users/home#index', as: :users

  match '/users/:id', to: 'users/home#show', via: 'get', as: :user
  # match '/users', to: 'users#index', via: 'get'

  resources :plans

  resources :training_sessions
  resources :workouts
  resources :exercises
  resources :workout_sets

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'home/index'
  root 'home#index'
end

app/views/layouts/_header.html.erb
 <head>
  <title>ProStrength</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag  "application", "jquery", "data-turbo-track": "reload", defer: true  %>
  <%= javascript_importmap_tags %>

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .feature-icon {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 4rem;
      height: 4rem;
      margin-bottom: 1rem;
      font-size: 2rem;
      color: #fff;
      border-radius: .75rem;
    }

    .icon-link {
      display: inline-flex;
      align-items: center;
    }
    .icon-link > .bi {
      margin-top: .125rem;
      margin-left: .125rem;
      transition: transform .25s ease-in-out;
      fill: currentColor;
    }
    .icon-link:hover > .bi {
      transform: translate(.25rem);
    }

    .icon-square {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 3rem;
      height: 3rem;
      font-size: 1.5rem;
      border-radius: .75rem;
    }

    .rounded-4 { border-radius: .5rem; }
    .rounded-5 { border-radius: 1rem; }

    .text-shadow-1 { text-shadow: 0 .125rem .25rem rgba(0, 0, 0, .25); }
    .text-shadow-2 { text-shadow: 0 .25rem .5rem rgba(0, 0, 0, .25); }
    .text-shadow-3 { text-shadow: 0 .5rem 1.5rem rgba(0, 0, 0, .25); }

    .card-cover {
      background-repeat: no-repeat;
      background-position: center center;
      background-size: cover;
    }

    /* body {
      background-image: linear-gradient(180deg, #eee, #fff 100px, #fff);
    } */

    .container {
      max-width: 960px;
    }

    .pricing-header {
      max-width: 700px;
    }
  </style>

</head>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <img src="#" class="rounded me-2" alt="#">
      <strong class="me-auto">System</strong>
      <small>11 mins ago</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<% if alert %>
  <div class="toast-header">
    <img src="#" class="rounded me-2" alt="#">
    <strong class="me-auto">System</strong>
    <small>11 mins ago</small>
    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
  <div class="toast-body">
    <%= alert %>
  </div>
</div>
<% end %>

app/views/layouts/_nav_links_for_admin_auth.html.erb
<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
  <li><a href="/plans" class="nav-link px-2 link-dark">Plans</a></li>
  <li><a href="/workouts" class="nav-link px-2 link-dark">Workouts</a></li>
</ul>

<form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
  <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
</form>

<div class="dropdown text-end">
  <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
    <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
  </a>
  <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
    <li><a class="dropdown-item" href="/plans/new">New plan...</a></li>
    <li><a class="dropdown-item" href="/exercises">Exercises</a></li>
    <li><a class="dropdown-item" href="/workouts">Workouts</a></li>
    <li><a class="dropdown-item" href="#">Settings</a></li>
    <li><a class="dropdown-item" href="/users/<%= current_admin.id %>">Profile</a></li>
    <li><hr class="dropdown-divider"></li>
    <li> <%= button_to "Sign out", destroy_user_session_path, method: :delete %></li>
  </ul>
</div>

app/views/layouts/_nav_links_for_user_auth.html.erb
<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
  <li><a href="/plans" class="nav-link px-2 link-dark">Plans</a></li>
  <li><a href="/workouts" class="nav-link px-2 link-dark">Workouts</a></li>
</ul>

<form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
  <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
</form>

<div class="dropdown text-end">
  <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
    <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
  </a>
  <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
    <li><a class="dropdown-item" href="#">Settings</a></li>
    <li><a class="dropdown-item" href="/users/<%= current_user.id %>">Profile</a></li>
    <li><%= link_to "Profile", profile_path(current_user), class: "dropdown-item"%></li>
    <li><hr class="dropdown-divider"></li>
    <li> <%= button_to "Sign out", destroy_user_session_path, method: :delete %></li>
  </ul>
</div>

app/views/layouts/_navbar_landing.html.erb
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
  <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
  </a>

  <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
    <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
    <li><a href="#features" class="nav-link px-2 link-dark">Features</a></li>
    <li><a href="#pricing" class="nav-link px-2 link-dark">Pricing</a></li>
    <li><a href="#about" class="nav-link px-2 link-dark">About</a></li>
  </ul>

  <div class="col-md-3 text-end">
    <a class="btn btn-outline-primary mr-2" href="/users/sign_in">Login</a>
  </div>
</header>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 5.0 %>

<% if user_signed_in? %>
  <%= render "layouts/sidebar_nav_user_auth"%>
<% elsif admin_signed_in? %>
  <%= render "layouts/sidebar_nav_admin_auth"%>
<% else %>
  <%= render "layouts/navbar_landing" %>
<% end %>

app/views/layouts/_sidebar_nav.html.erb
<div class="col-sm-auto bg-light sticky-top">
  <div class="d-flex flex-sm-column flex-row flex-nowrap bg-light align-items-center sticky-top">
    <a href="/" class="d-block p-3 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only">
      <i class="bi-bootstrap fs-1"></i>
    </a>
    <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center justify-content-between w-100 px-3 align-items-center">
      <li class="nav-item">
        <a href="/" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
          <i class="bi-house fs-1"></i>
        </a>
      </li>
      <li>
        <a href="/training_sessions" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Dashboard">
          <i class="bi-speedometer2 fs-1"></i>
        </a>
      </li>
      <li>
        <a href="/workouts" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Workouts">
          <i class="bi-table fs-1"></i>
        </a>
      </li>
      <li>
        <a href="/exercises" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Exercises">
          <i class="bi-heart fs-1"></i>
        </a>
      </li>
      <li>
        <a href="/users" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Community">
          <i class="bi-people fs-1"></i>
        </a>
      </li>
    </ul>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi-person-circle h2"></i>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="/users/<%= current_user.id %>">Profile</a></li>
        <li> <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
      </ul>
    </div>

  </div>
</div>

app/views/layouts/_sidebar_nav_admin_auth.html.erb
<div class="col-sm-auto bg-light sticky-top">
  <div class="d-flex flex-sm-column flex-row flex-nowrap bg-light align-items-center sticky-top">
    <a href="/" class="d-block p-3 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only">
      <i class="bi-bootstrap fs-1"></i>
    </a>
    <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center justify-content-between w-100 px-3 align-items-center">
      <li class="nav-item">
        <a href="/" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
          <i class="bi-house fs-1"></i>
        </a>
      </li>
      <li>
        <a href="/training_sessions" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Dashboard">
          <i class="bi-speedometer2 fs-1"></i>
        </a>
      </li>
      <li>
        <a href="/workouts" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Workouts">
          <i class="bi-table fs-1"></i>
        </a>
      </li>
      <li>
        <a href="/exercises" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Exercises">
          <i class="bi-heart fs-1"></i>
        </a>
      </li>
      <li>
        <a href="/admins" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Users">
          <i class="bi-people fs-1"></i>
        </a>
      </li>
    </ul>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi-person-circle h2"></i>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="/users/<%= current_admin.id %>">Profile</a></li>
        <li> <%= button_to "Sign out", destroy_admin_session_path, method: :delete, class: "dropdown-item" %></li>
      </ul>
    </div>

  </div>
</div>

app/views/layouts/_sidebar_nav_user_auth.html.erb
<div class="col-sm-auto bg-light sticky-top">
  <div class="d-flex flex-sm-column flex-row flex-nowrap bg-light align-items-center sticky-top">
    <a href="/" class="d-block p-3 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only">
      <i class="bi-bootstrap fs-1"></i>
    </a>
    <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center justify-content-between w-100 px-3 align-items-center">
      <li class="nav-item">
        <a href="/" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
          <i class="bi-house fs-1"></i>
        </a>
      </li>
      <li>
        <a href="/training_sessions" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Trainings">
          <i class="bi-table fs-1"></i>
        </a>
      </li>
      <% if current_user.coach? %>
        <li>
          <a href="/metrics" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Metrics">
            <i class="bi-speedometer2 fs-1"></i>
          </a>
        </li>
        <li>
          <a href="/workouts" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Exercises">
            <i class="bi-heart fs-1"></i>
          </a>
        </li>
        <li>
          <a href="/users" class="nav-link py-3 px-2" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Community">
            <i class="bi-people fs-1"></i>
          </a>
        </li>
      <% end %>
    </ul>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi-person-circle h2"></i>
      </a>
      <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><%= link_to "Profile", user_path(current_user.id), class: "dropdown-item"%></li>
        <li> <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
      </ul>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/header" %>
  <body>
    <%= render "layouts/svg_symbols" %>

    <div class="container-fluid">
      <div class="row">

        <%= render "layouts/navigation" %>

        <div class="col-sm p-3 min-vh-100">
          <div class="container-sm">
            <%= render "layouts/messages" %>
            <%= yield %>
          </div>

        </div>
      </div>
    </div>
  </body>
</html>